set_property PACKAGE_PIN N15 [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property PACKAGE_PIN J2 [get_ports reset_rtl_0]
set_property IOSTANDARD LVCMOS25 [get_ports reset_rtl_0]

set_property -dict { PACKAGE_PIN A16 IOSTANDARD LVCMOS33 } [get_ports {uart_rtl_0_txd}]
set_property -dict { PACKAGE_PIN B16 IOSTANDARD LVCMOS33 } [get_ports {uart_rtl_0_rxd}]

set_property -dict { PACKAGE_PIN V17 IOSTANDARD TMDS_33 } [get_ports {HDMI_0_tmds_clk_n}]
set_property -dict { PACKAGE_PIN U16 IOSTANDARD TMDS_33 } [get_ports {HDMI_0_tmds_clk_p}]
set_property -dict { PACKAGE_PIN U18 IOSTANDARD TMDS_33 } [get_ports {HDMI_0_tmds_data_n[0]}]
set_property -dict { PACKAGE_PIN R17 IOSTANDARD TMDS_33 } [get_ports {HDMI_0_tmds_data_n[1]}]
set_property -dict { PACKAGE_PIN T14 IOSTANDARD TMDS_33 } [get_ports {HDMI_0_tmds_data_n[2]}]
set_property -dict { PACKAGE_PIN U17 IOSTANDARD TMDS_33 } [get_ports {HDMI_0_tmds_data_p[0]}]
set_property -dict { PACKAGE_PIN R16 IOSTANDARD TMDS_33 } [get_ports {HDMI_0_tmds_data_p[1]}]
set_property -dict { PACKAGE_PIN R14 IOSTANDARD TMDS_33 } [get_ports {HDMI_0_tmds_data_p[2]}]

# OV7670 camera on PMOD.
set_property -dict { PACKAGE_PIN E14 IOSTANDARD LVCMOS33 } [get_ports clk_out2_0]
set_property -dict { PACKAGE_PIN J13 IOSTANDARD LVCMOS33 } [get_ports cam_scl_0]
set_property -dict { PACKAGE_PIN J14 IOSTANDARD LVCMOS33 PULLUP true } [get_ports cam_sda_0]
set_property -dict { PACKAGE_PIN F14 IOSTANDARD LVCMOS33 } [get_ports cam_vsync_0]
set_property -dict { PACKAGE_PIN E15 IOSTANDARD LVCMOS33 } [get_ports cam_href_0]
set_property -dict { PACKAGE_PIN F15 IOSTANDARD LVCMOS33 } [get_ports cam_pclk_0]
set_property -dict { PACKAGE_PIN H13 IOSTANDARD LVCMOS33 } [get_ports cam_pwdn_0]
set_property -dict { PACKAGE_PIN J15 IOSTANDARD LVCMOS33 } [get_ports {cam_d_0[0]}]
set_property -dict { PACKAGE_PIN K14 IOSTANDARD LVCMOS33 } [get_ports {cam_d_0[1]}]
set_property -dict { PACKAGE_PIN G18 IOSTANDARD LVCMOS33 } [get_ports {cam_d_0[2]}]
set_property -dict { PACKAGE_PIN H18 IOSTANDARD LVCMOS33 } [get_ports {cam_d_0[3]}]
set_property -dict { PACKAGE_PIN J16 IOSTANDARD LVCMOS33 } [get_ports {cam_d_0[4]}]
set_property -dict { PACKAGE_PIN K16 IOSTANDARD LVCMOS33 } [get_ports {cam_d_0[5]}]
set_property -dict { PACKAGE_PIN H17 IOSTANDARD LVCMOS33 } [get_ports {cam_d_0[6]}]
set_property -dict { PACKAGE_PIN H16 IOSTANDARD LVCMOS33 } [get_ports {cam_d_0[7]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cam_pclk_0_IBUF]
create_clock -period 41.667 -name cam_pclk [get_ports cam_pclk_0]
set_false_path -from [get_clocks cam_pclk] -to [get_clocks *]
set_false_path -from [get_clocks *] -to [get_clocks cam_pclk]

# On-board slide switches.
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS25} [get_ports {sw[0]}]
set_property -dict {PACKAGE_PIN F2 IOSTANDARD LVCMOS25} [get_ports {sw[1]}]
set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVCMOS25} [get_ports {sw[2]}]
set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVCMOS25} [get_ports {sw[3]}]
set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS25} [get_ports {sw[4]}]
set_property -dict {PACKAGE_PIN D2 IOSTANDARD LVCMOS25} [get_ports {sw[5]}]
set_property -dict {PACKAGE_PIN D1 IOSTANDARD LVCMOS25} [get_ports {sw[6]}]
set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS25} [get_ports {sw[7]}]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS25} [get_ports {sw[8]}]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS25} [get_ports {sw[9]}]
set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS25} [get_ports {sw[10]}]
set_property -dict {PACKAGE_PIN A6 IOSTANDARD LVCMOS25} [get_ports {sw[11]}]
set_property -dict {PACKAGE_PIN C7 IOSTANDARD LVCMOS25} [get_ports {sw[12]}]
set_property -dict {PACKAGE_PIN A7 IOSTANDARD LVCMOS25} [get_ports {sw[13]}]
set_property -dict {PACKAGE_PIN B7 IOSTANDARD LVCMOS25} [get_ports {sw[14]}]
set_property -dict {PACKAGE_PIN A8 IOSTANDARD LVCMOS25} [get_ports {sw[15]}]

# On-board LEDs.
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports {led[2]}]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports {led[3]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33} [get_ports {led[4]}]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS33} [get_ports {led[5]}]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports {led[6]}]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS33} [get_ports {led[7]}]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33} [get_ports {led[8]}]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports {led[9]}]
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS33} [get_ports {led[10]}]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports {led[11]}]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33} [get_ports {led[12]}]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports {led[13]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports {led[14]}]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports {led[15]}]

# On-board capture button.
set_property -dict {PACKAGE_PIN J1 IOSTANDARD LVCMOS25} [get_ports {capture}]
